-- 코드를 입력하세요
SELECT NAME
        ,DATETIME
FROM ANIMAL_INS AI JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
) TMP
ON AI.ANIMAL_ID = TMP.ANIMAL_ID
ORDER BY DATETIME
LIMIT 3;