-- 코드를 입력하세요
WITH TEMP AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_OUTS)
)

SELECT NAME, 
        A.DATETIME
FROM TEMP T JOIN ANIMAL_INS A 
    ON T.ANIMAL_ID = A.ANIMAL_ID
ORDER BY A.DATETIME
LIMIT 3;