-- 코드를 입력하세요
SELECT P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN (
                            SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
                            FROM FOOD_ORDER
                            WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
                            GROUP BY PRODUCT_ID
                        ) O
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;

# SELECT P.PRODUCT_ID, 
#         PRODUCT_NAME, 
#         SUM(PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY P.PRODUCT_ID, PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;