-- 코드를 입력하세요
SELECT F.CATEGORY
        ,F.PRICE AS MAX_PRICE
        ,F.PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE
                            FROM FOOD_PRODUCT
                            WHERE CATEGORY IN ('과자', '국', ' 김치', '식용유')
                            GROUP BY CATEGORY) T
    ON F.CATEGORY = T.CATEGORY AND F.PRICE = T.PRICE
ORDER BY MAX_PRICE DESC;

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY PRICE DESC;